# Numpy

In [1]:
import numpy as np

## The Basics

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [6]:
# Get Dimension
a.ndim

1

In [7]:
# Get Shape
a.shape

(3,)

In [8]:
# Get Type
a.dtype

dtype('int32')

In [9]:
# Get Size
a.itemsize

4

In [11]:
# Get Total Size
a.nbytes

12

## Accessing/Changing specific elements, rows, columns, etc

In [35]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [13]:
# Get a specific element [r, c]
a[1, 5]

13

In [14]:
a[1,-2]

13

In [15]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [17]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [18]:
a[0, 1:-1:2]

array([2, 4, 6])

In [20]:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [22]:
a[:,2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [23]:
# 3D example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
# Get specific element (work outside in)
b[0,1,1]

4

In [26]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [29]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing Different Types of Arrays

In [30]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
# All 1s matrix
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
# Any other number
np.full((2,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [40]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [43]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.44023944, 0.89977681],
       [0.34228592, 0.25394495],
       [0.29237814, 0.56421377],
       [0.52465598, 0.99748349]])

In [44]:
np.random.rand(4,2,3)

array([[[0.46068501, 0.53636537, 0.62484117],
        [0.78332908, 0.40473536, 0.57960829]],

       [[0.47188634, 0.32795774, 0.33707609],
        [0.70194824, 0.26996127, 0.00635573]],

       [[0.68033831, 0.01700932, 0.37637037],
        [0.49130345, 0.28743338, 0.61501993]],

       [[0.31045142, 0.48031707, 0.70483816],
        [0.62873544, 0.89215773, 0.00292857]]])

In [48]:
# Random integer values
np.random.randint(7, size=(3,3))

array([[2, 4, 5],
       [4, 1, 0],
       [6, 6, 6]])

In [50]:
# Get identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [57]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
